- core/Makefile
with this, you can now do
```shell
$ cd ./core
$ make
```
and get a compiled `libcore.a` static lib :)
> fix Core Makefile

- README.md
Just adding a ✅, for the file format that's now documented.
> Update README - file format now documented

- README.md
Current link in README is expired. Change it to persistent discord link hosted on the website (https://cu.bzh/discord).
> refactor: update discord link in readme

- cli/blocks.cpp
- cli/blocks.hpp
- cli/combine.cpp
- cli/main.cpp
- cli/xcode/cli.xcodeproj/project.pbxproj
- cli/xcode/cli.xcodeproj/xcshareddata/xcschemes/cli.xcscheme
- core/scene.h
Adds a command to count blocks. 
⚠️ only support `.3zh` input files, we should add support for `.vox`.
> CLI: add command to count blocks

- core/inputs.c
- core/inputs.h
Keyboard inputs were only allowed to be posted separately (char codes & key codes). 
Plus, all inputs are currently pushed in queues pulled by interested listeners.
It works well in some cases, to work with ImGUI or when we need to combine several mouse events happening within one tick. 
But to expose keyboard inputs in the Lua sandbox, I added another kind of listener (`input_keyboard_listener_new`) that allows to get complete keyboard input information as it comes in. (posted through `postKeyboardInput`).
Also added `input_char_code_to_string` to `inputs.h/.c`, it's very useful to decode wide chars.
> inputs: receiver for complete keyboard inputs

- core/mutex.c
- core/mutex.h
- core/shape.c
- core/shape.h
- core/tests/xcode/unit_tests.xcodeproj/project.pbxproj
Fixes a crash when calling shape_make() in different threads. 
It was necessary to use a mutex in `getValidShapeId()`. 
Also removed an index that needed to be made thread safe too, but realized it wasn't even useful for anything.
> make shape_make() thread safe

- lua/docs/content/reference/animation.yml
- lua/docs/content/reference/camera.yml
- lua/docs/content/reference/collisiongroups.yml
- lua/docs/content/reference/color.yml
- lua/docs/content/reference/index.yml
- lua/docs/content/reference/light.yml
- lua/docs/content/reference/number2.yml
- lua/docs/content/reference/number3.yml
- lua/docs/content/reference/object.yml
- lua/docs/content/reference/player.yml
- lua/docs/content/reference/quad.yml
- lua/docs/content/reference/rotation.yml
- lua/docs/content/reference/shape.yml
- lua/docs/content/reference/text.yml
To be merged with 0.0.52 release.
Reference changelog,
- new `Animation` type
- new `Rotation` type
- added `camera:WorldToScreen(number3)` and `camera:ScreenToRay(number2)`
- added `number3:Angle(number3)`
- added `number3:Lerp`, `number2:Lerp`, `color:Lerp`
- added `number3:Set`, `number2:Set`, `color:Set`
- added `quad.Size`, `shape.Size`
- extended signatures for `object:RotateLocal`, `RotateWorld`, `RotationLocalToWorld`, `RotationWorldToLocal` and `number3:Rotate`
- moved `shape/player.ShadowCookie` to `object.ShadowCookie`, and its workings has been updated
- increased number of available `Layers` from `8` to `12`
- increased number of available `CollisionGroups` from `8` to `12`
- fixed a docs error in `shape.Palette`
> Docs 0.0.52

- lua/modules/chat.lua
Fixes https://linear.app/cubzh/issue/CUB-725/cant-start-a-command-with-a
> Chat: add `//a` for devs

- cli/cmake/CMakeLists.txt
without this the build only works with docker
> CMAKE: fixed path for non-docker builds

- core/serialization_v6.c
looks like the file that vengi is creating doesn't contain a valid size chunk yet
> CORE: catch invalid files with missing size chunk

- lua/modules/signup.lua
- lua/modules/uitheme.lua
- "Who are you?" ➡️ "Sign Up". 
- increased contrast for text input placeholders
One small contribution to better comply with Families Policy Requirements.
> Signup screen: new form title + increased contrast for text input placeholders

- lua/modules/signup.lua
fixes https://linear.app/cubzh/issue/CUB-1004/overlap-in-profile-creation
> signup form : shorten error message

- lua/modules/cubzh.lua
fixes https://linear.app/cubzh/issue/CUB-1023/hub-claire-npc-scales-up-when-we-deploy-the-glider
> module cubzh.lua : fix NPC "bounce" animation

- lua/modules/ease.lua
For `Rotation` & `Color` types, we made `p` a reference of `from`. 
So `p:Lerp` would actually change the value of `from`. 
`from` would become closer to `to` over time, speeding up animation in a way for both these types. 
fixed using dedicated variables (removed `p = from`)
Improvement: moved local variables outside of the Tick function.
> ease module: fix easing rotations & colors

- core/shape.c
Fixes error in `_shape_compute_size_and_origin`.
Could lead to lost cubes in some situations.
Fixes CUB-972
> Fix lost cubes

- core/magicavoxel.c
In the docs, it seems to indicate that RGBA chunk's size is always supposed to be 1024 (256 x 4). 
But it's not always the case when .vox come from softwares other than Magicavoxel. 
Making it more permissive, considering provided chunk size.
> vox file import: fix when RGBA chunk doesn't have 256 entries

- lua/modules/uikit.lua
This is a recent regression due to how we now manage several potential impacts across ui layers, introduced for scroll areas. Buttons would not receive cancel events when releasing pointer outside the area.
> uikit: fix onCancel not called in when it should

- lua/modules/api.lua
- lua/modules/friends.lua
- lua/modules/item_details.lua
- lua/modules/item_grid.lua
- lua/modules/modal.lua
- lua/modules/profile.lua
- lua/modules/ui_container.lua
- lua/modules/uikit.lua
- lua/modules/world_details.lua
- lua/modules/worlds.lua
- Removed unnecessary `nil` checks used to early return within supposably removed uikit nodes. (checks should be made upstream, same for cancelling requests, timers and listeners)
- Improved friends modal
- fixed ui_container (no more stack overflows)
Fixes CUB-1170
Fixes CUB-1134 (I think it does fix it)
Fixes CUB-1079
> item_grid / worlds/ world_details : cleanup + cancel requests, timers ans listeners

- lua/modules/signup.lua
Using uppercase A-Z characters triggers an error on signup screen saying only a-z characters are allowed. 
It's misleading for some users, according to recent feedback. 
The solution here is to force lowercase characters on input. 
With this PR, typing "Bill" now automatically displays "bill".
> Signup: auto-lower text input

- lua/modules/item_editor.lua
Repro,
- Open an item
- Long press to begin continuous edition
- Add/Remove some blocks continuously
- Release long press
Observed: undo button doesn't activate (if long press is the first action of the list of actions)
> Item Editor: fix undo not available if first action is a long press

- lua/modules/item_editor.lua
Fixes CUB-1039
Fixes CUB-1038
Fixes,
- autosave timer not triggering when adding, removing, or importing/replacing a subshape
- autosave timer wrongly triggering when selecting a subshape, using pipette, or placing mirror
> Item Editor: fix autosave

- lua/docs/content/cubzhcheatsheet.yml
It looks like there's a small error with the variable pointer that doesn't exist.
> Fix Raycast typo (docs)

- lua/modules/camera_modes.lua
Eye blinks have bothering a few devs who're using first person camera mode through `camera_modes` module...
Here's a fix to hide eye lids when in first person.
> hide eye lids in first person camera mode

- lua/modules/world_editor.lua
I couldn't edit the scale of a map due to this, it's a small fix.
> world editor: fix scale row width in settings

- core/quad.c
The `quad_get_data_hash` function is currently responsible for high CPU usage because of it being mandatorily called as map key lookups. Caching the hash makes this a non-issue
> Cache quad data hash

- deps/xptools/include/filesystem.hpp
- deps/xptools/windows/filesystem_windows.cpp
- added `normalizePath` to xptools (`vx::fs`)
- implemented it only for windows (as it is not used elsewhere for now, and later on we might upgrade to C++17 and use the included `filesystem` functions from the standard library)
> Windows fix bundle and storage file access

- lua/modules/cubzh.lua
- lua/modules/item_details.lua
- lua/modules/menu.lua
This PR fixes a few regressions for items. 
Fixes #613
- Adds "all items" button on item rows to browse all items: 
- Adds "Items" button on pause menu when in dev mode: 
- Adds button to edit item description:
> Fix item regressions

- core/shape.c
- deps/xptools/common/HttpCookie.cpp
- Fixes memory leaks in `HttpCookie.cpp` (⚠️ `cJSON_Delete` vs `cJSON_free`)
- Fixes memory leak in `_shape_compute_size_and_origin` (iterator not freed in early return condition)
> Fix memory leaks

- lua/modules/friends.lua
fixes #641 
I just removed this condition: `if usr.username ~= "" then`
> fix listing of friend requests by users without username

- lua/modules/uikit.lua
Fixes https://github.com/cubzh/cubzh/issues/638
There was a missing condition in the system to register scroll for subsequent drag events when a "pointer down" responder is within a scroll. Forgot to early return when the closest responder itself isn't within a scroll. 
We couldn't escape that alert, now it works:
https://github.com/user-attachments/assets/4493f608-38d5-4c95-891b-bfaffb7c254b
> Fix buttons not working when displayed over scroll areas (not within)

- lua/modules/avatar.lua
Dono is not (wrongfully) blue anymore
when undefined, `data.skinColorIndex` comes back with `0` value, not `-1`
> avatar : fix skin color (edge case)

- .github/workflows/lua_docs_deploy_prod.yml
- ci/lua_docs_deploy_prod/main.go
the last PR merge failed to auto-redeploy the Lua docs:
https://github.com/cubzh/cubzh/actions/runs/11427263668/job/31791186822
Because last PR (https://github.com/cubzh/cubzh/pull/689) introduced the use of `./bundle/audio` files in the docs instead of duplicating them in `./lua/docs/content/audio`
This PR fixes the deploy by adding the missing `./bundle/audio` in the docker build context.
- I already ran the deploy process on my machine to test my fix, so the docs are already up to date here : https://docs.cu.bzh 
- The only change in the YAML file is this line : `go-version: ">=1.23"` & indent size
> CI/CD : update Lua docs deploy

- core/camera.c
- core/camera.h
- core/light.c
- core/light.h
- core/mesh.c
- core/quad.c
- core/quad.h
- core/scene.c
- core/scene.h
- core/serialization.c
- core/serialization_v5.c
- core/serialization_v6.c
- core/serialization_vox.c
- core/shape.c
- core/shape.h
- core/tests/test_shape.h
- core/transform.c
- core/transform.h
- core/world_text.c
- core/world_text.h
- lua/modules/cubzh.lua
- lua/modules/massloading.lua
- lua/modules/transformgizmo.lua
- lua/modules/ui_avatar.lua
- lua/modules/uikit.lua
- lua/modules/world.lua
This PR,
- adds a universal `o:Copy({ recurse=false })`
- improves on the recursion lock to handle nested `o:Recurse()` calls
> Lua Object improvements

- lua/modules/camera.lua
`Camera.Behavior.rotationTarget` should accept `Rotation` type.
> Camera.Behavior.rotationTarget should accepts Rotation type
