bliporg/blip

.gitignore
core/tests/xcode/unit_tests.xcodeproj/project.pbxproj
core/tests/xcode/unit_tests.xcodeproj/project.xcworkspace/contents.xcworkspacedata
core/tests/xcode/unit_tests.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
core/tests/xcode/unit_tests.xcodeproj/xcuserdata/gaetan.xcuserdatad/xcschemes/xcschememanagement.plist

Unit Tests : add Xcode project

---

.gitignore
core/tests/README.md
dockerfiles/ubuntu_build_env.Dockerfile

It builds ~15% faster on my machine.

unit tests : use faster Ninja build system

---

core/color_atlas.c
core/color_palette.c
core/colors.c
core/colors.h
core/transform.c
core/utils.h

Support PR for https://github.com/voxowl/particubes-private/pull/3237

Lua text support

---

.github/workflows/ci.yml
README.md

Add CI badge for main branch

---

.gitignore
core/tests/visual_studio/Cubzh Core Unit Tests.vcxproj
core/tests/visual_studio/Cubzh Core Unit Tests.vcxproj.filters

- increase warning level
- update gitignore

Update windows project

---

core/rigidBody.c
core/rigidBody.h
core/scene.c

Fixes https://github.com/voxowl/particubes-private/issues/3379

Fix static collider culling

---

core/asset.h
core/color_atlas.c
core/color_palette.c
core/color_palette.h
core/colors.c
core/colors.h
core/resource.h
core/serialization.c
core/serialization.h
core/serialization_v5.c
core/serialization_v5.h
core/serialization_v6.c
core/serialization_v6.h
core/shape.c
core/shape.h
core/transform.c
core/utils.h

This branch contains required changes & additions for the next version of Cubzh (0.0.48).

Needed for 0.0.48

---

.github/workflows/apply_format.yml
ci/README.md
ci/core_unit_tests/main.go
ci/format/main.go

Add option for applying format changes

---

ci/format/main.go
core/hash_uint32_int.c
core/serialization.c
core/serialization.h
core/serialization_v5.c
core/serialization_v5.h
core/serialization_v6.c
core/serialization_v6.h
core/shape.c

This PR fixes a bunch of memory leaks.

Fix memory leaks

---

core/tests/test_list.c
core/tests/test_shape.h

Urgent:
- test creating multiple shapes (using 1 color) , and see if the global palette always contains 1 color (and not more)

Core tests: shape

---

ci/core_unit_tests/go.mod
ci/core_unit_tests/go.sum
ci/core_unit_tests/main.go
ci/format/go.mod
ci/format/go.sum
core/tests/test_list.c
core/vertextbuffer.c

update to latest dagger and minor fixes (typo & sleep during race condition in dagger preventing logs to be displayed when there is an error in unit tests)

CI : update to dagger 0.4.2 & minor fixes

---

cli/cmake/CMakeLists.txt
cli/combine.cpp
cli/combine.hpp
cli/main.cpp
cli/xcode/cli.xcodeproj/project.pbxproj
cli/xcode/cli.xcodeproj/project.xcworkspace/contents.xcworkspacedata
cli/xcode/cli.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
cli/xcode/cli.xcodeproj/xcshareddata/xcschemes/cli.xcscheme
core/magicavoxel.c
core/magicavoxel.h
core/tests/cmake/CMakeLists.txt
deps/cxxopts/include/cxxopts.hpp

Adds cli code + Xcode project to build it on macOS. 
We need to add ways to build it on other platforms (@vitawrap? 🙂)
But let's merge this one already, it's a good start!

add cli + combine command

---

lua/docs/content/reference/data.yml
lua/docs/content/reference/index.yml

Lua docs: Data

---

core/color_palette.c
core/color_palette.h
core/shape.c
core/shape.h

I needed this to be able to load shapes and palette asynchronously then import them into the running game.

Add functions to replace shape and palette color atlases

---

ci/core_unit_tests/main.go

CI (core_unit_tests): show more compilation errors in logs

---

lua/docs/content/reference/box.yml
lua/docs/content/reference/camera.yml
lua/docs/content/reference/clouds.yml
lua/docs/content/reference/index.yml
lua/docs/content/reference/object.yml
lua/docs/content/reference/screen.yml

To be merged with the 0.0.49 release

Docs 0.0.49

---

core/config.h
core/shape.c

Fixes https://github.com/voxowl/particubes-private/issues/3703

Fix shape max size

---

core/rigidBody.c

Fixes https://github.com/voxowl/particubes-private/issues/3693

Fix trigger OnCollisionBegin

---

core/shape.c

Fixes https://github.com/voxowl/particubes-private/issues/3711

Empty shape allocation from arbitrary origin

---

lua/docs/content/cubzhcheatsheet.yml
lua/docs/content/reference/object.yml

fixes https://github.com/cubzh/cubzh/issues/174

lua-docs : fix typos

---

core/fifo_list.c
core/magicavoxel.c
core/shape.c
core/tests/test_shape.h
core/tests/visual_studio/Cubzh Core Unit Tests.sln
core/tests/visual_studio/Cubzh Core Unit Tests.vcxproj
core/vertextbuffer.c

Visual Studio: use the same warnings as in the CI

---

lua/docs/content/reference/audiosource.yml

This should be merged after the `0.0.49 patch 6` update has been published.
- update AudioSource constructor signature

Lua docs : `0.0.49 patch 6` update 

---

lua/docs/content/reference/object.yml

This documentation has been missing for a long time. I wouldn't have known this function existed if not for other people having used it.

Added pivot documentation

---

core/config.h

Making default bounciness & friction the same for all items.

Update default bounciness & friction for items

---

core/block.c
core/block.h
core/blockChange.c
core/blockChange.h
core/index3d.c
core/octree.c
core/serialization_v6.c
core/shape.c
core/shape.h
core/tests/test_blockChange.h
core/tests/test_shape.h
core/tests/test_transaction.h
core/tests/visual_studio/Cubzh Core Unit Tests.vcxproj
core/tests/visual_studio/Cubzh Core Unit Tests.vcxproj.filters
core/transaction.c
core/transaction.h

The fix is in that commit: 7cfd04049280b4504106e150ad2370ec365b31a9
The other one (91ea9e3fc4668d5a3673f20bc2d9efa10dcefcb2) are assert and small improvements added while debugging.

Index3d crash fix

---

lua/modules/equipments.lua

simple fix equipments.lua

---

lua/modules/empty_table.lua

Update empty_table.lua (fixes typo)

---

lua/modules/item_grid.lua

Providing accessors to update cell size and layout in item_grid module.

fixes in item_grid module (cell layout)

---

lua/modules/player.lua

`CastRay` was not returned properly because key was not listed.

fix Player:CastRay

---

lua/modules/ai.lua

Fixes errors when using quotes in context and prompts.

ai module: escape quotes

---

lua/docs/content/modules/index.yml
lua/docs/content/reference/ai.yml
lua/docs/content/reference/index.yml
lua/modules/ai.lua

- Documentation for AI module
- ai module is listed among other modules
- `AI` shortcut to `require("ai")` has been added to the reference
- Fixed in ai module to get rid of all `luacheck` warnings

ai module documentation

---

core/rigidBody.h

I needed to add this PhysicsMode fields in Events to be supported.

RigidbodyMode values

---

lua/modules/bundle.lua
lua/modules/chat.lua
lua/modules/config.lua
lua/modules/cubzh.lua
lua/modules/localevent.lua
lua/modules/menu.lua
lua/modules/multi.lua
lua/modules/player.lua
lua/modules/textbubble.lua
lua/modules/textbubbles.lua
lua/modules/uikit.lua

Core PR for online hub and chat improvements
- adds `bundle` module to load Shapes from bundle
- adds `config` to parse/merge config tables easily
- `textbubble` module becomes `textbubbles` + fixes
- `chat` module: decouple modal content from standalone chat console node

Online hub and chat improvements

---

lua/modules/avatar.lua

Allows to replace parts of an avatar instead of re-creating the whole thing. 
Fixing situations where we could lose parented objects and properties.

avatar module: add option to replace existing avatar

---

core/config.h
lua/modules/localevent.lua
lua/modules/menu.lua

- Adds Hub world ID in config
- New local event to close loading popup when World fails to connect

Hub world ID in config + FailedToLoadWorld local event

---

core/serialization_v6.c

fixed missing cursor updates in case of failed mallocs or invalid data in the files
for the shape name node the cursor update was also missing in the case of successful parsing the name. this lead to further problems but wasn't noticed yet, because the name was always saved last in the save function
also fixes a mem leak for the name string - i wonder if a `char string[256]` buffer on the stack wouldn't be better here, as the max length is limited by the byte width anyway. that would prevent further or future memory leaks (I haven't check all of the code paths)

CORE: handle failed malloc in chunk_v6_read_shape

---

cli/blocks.cpp
cli/shape_point.cpp

`.octree` field doesn't exist anymore

cli : fix compilation

---

core/shape.c
core/transaction.c
core/transaction.h

fix:
There was a double `index3d_iterator_next(it);` on each iteration.

fix shape undo transaction

---

lua/docs/content/reference/screen.yml

⚠️ To be merged after Cubzh 0.0.54 is released.

Lua reference doc : add Screen.Size field

---

lua/modules/avatar.lua
lua/modules/item_details.lua
lua/modules/profile.lua

https://github.com/cubzh/cubzh/pull/359/files#diff-7a905cd1e6a8c35d4b2bb16799a0554b1e03dadd3231a5d5e05f7f94b2dcd9c5R517-R520

fix avatar preview in profile screen for users not having all equipments

---

core/rigidBody.c

This reverts commit 1c36d82c761bdbbe6d6fbfe0c7183516af03e02c.

Revert "physics : add motion clamp"

---

lua/modules/profile.lua

The issue was that the width we took into account was the large one with the grid

Profile: fix link buttons width

---

lua/modules/menu.lua

Center the number of likes in pause menu

---

lua/modules/colorpicker.lua
lua/modules/palette.lua
lua/modules/uikit.lua

palette & colorpicker: request per block collisions

---

lua/modules/avatar.lua
lua/modules/profile.lua
lua/modules/ui_avatar.lua

should be easy to review , commit by commit

fix avatar preview refresh in profile window

---

lua/modules/cubzh.lua

module cubzh.lua : fix other players' backpack size

---

lua/modules/cubzh.lua

- Only trigger NPC dialog for local player
- Fixes glider no shown for other connected players

Hub small fixes

---

lua/modules/cubzh.lua
lua/modules/object_skills.lua

It seems that the issue came form setting Player.Rotation.X to 0.06. Do we really need Player..Rotation to be a Number3?

Fix jump after respawn

---

ci/core_unit_tests/main.go
ci/format/main.go
core/chunk.c

replace "wether" by "whether"

---

core/inputs.c
core/rtree.c
core/serialization_v5.c
core/serialization_v6.c
core/shape.c
core/vertextbuffer.c
lua/modules/menu.lua

Capture controls when title screen is shown.

Fix controls on title screen

---

lua/docs/content/cubzhcheatsheet.yml

Updated The Documentation Error Made At OnMessage Event

Updated cubzhcheatsheet.yml

---

lua/modules/menu.lua
lua/modules/ui_pointer.lua

- Adds `Menu:ShowFriends()`
- Adds `Menu:ShowProfile()`
- Adds `Menu:Highlight()` (highlights Cubzh menu button)
- Adds `Menu:HighlightFriends()` 
- Adds `Menu:HighlightProfile()` 
- Adds `Menu:RemoveHighlight()` 
- Adds `ui_pointer` module (used to highlight menu components)
- Removes commented code in menu.lua
https://github.com/cubzh/cubzh/assets/6775074/174961ac-30f6-471b-98b6-aca815737ce4

Menu accessors

---

core/config.h
core/rigidBody.c

Improved physics replacements

---

lua/modules/menu.lua

- Adds Menu:ShowWorlds()
- Adds Menu:ShowItems()

add Menu:ShowWorlds / Menu:ShowItems

---

lua/modules/cubzh.lua
lua/modules/localevent.lua
lua/modules/massloading.lua
lua/modules/world_editor.lua
lua/modules/world_editor_common.lua

Private: https://github.com/voxowl/particubes-private/pull/4555

LoadWorld with callbacks

---

lua/modules/api.lua
lua/modules/item_grid.lua

new query parameters "page" & "perPage"

update requests for worlds

---

lua/modules/avatar.lua
lua/modules/menu.lua

contributes to https://linear.app/cubzh/issue/CUB-1083/the-chat-avatar-is-not-updated-when-changing-hair

top bar avatar : fix update when avatar colors are changed (skin, eyes, nose, mouth)

---

lua/modules/menu.lua
lua/modules/modal.lua
lua/modules/signup.lua
lua/modules/system_api.lua
lua/modules/ui_badge.lua

- Asking for email in main menu if none provided
- Not asking for password anymore in signup form

Email form

---

lua/modules/controls.lua

- Fix wrong touch indicator scale first time it is displayed
- Fix drag not resuming after drag2

Control fixes

---

lua/modules/signup.lua

- Username check request now sent away if needed when pressing Sign Up button (noTimer option)
- `checkUsername()` now cancels ongoing timer and/or sent request before anything else
- `usernameInfo.pos.X` updated before it may eventually be destroyed by callback

Signup screen fixes

---

lua/modules/cubzh.lua
lua/modules/ui_toast.lua

- Adds drink truck + Discord sign
- Fixes changing room & tele-porter triggers
Fixes CUB-1122

Hub 0.0.62

---

lua/modules/equipments.lua
lua/modules/friends.lua
lua/modules/ui_container.lua

onPress on a cell, trigger "onPress" callback (to change color for example) 
Use cache for avatars
Timer Request to avoid loading everything when scrolling fast
Title medium size, username small
Bigger avatar

Friends Scroll Improvements

---

lua/modules/friends.lua
lua/modules/item_grid.lua
lua/modules/social.lua

Menu fixes

---

lua/modules/uikit.lua

* Removed print "image taken into account"
* Now setting image from config with node:setImage

fix setImage and loading image from config

---

lua/modules/item_details.lua

- fixes async description loading on Item Details screen (from the item gallery)
- remove 1 HTTP request and use the `api:getItem()` for everything

item detail : fix description refresh

---

lua/modules/item_editor.lua

Item Editor: fix initial zoom

---

lua/modules/item_editor.lua
lua/modules/palette.lua

Fixes CUB-798
Fixes CUB-268
Fixes CUB-1085

Item Editor: shared palette & fixes

---

core/rigidBody.c
core/shape.c
core/shape.h

Physics: use model collider for per-block shapes

---

lua/modules/item_editor.lua

Item Editor: fix highlight & raycasts cleanup

---

lua/modules/item_editor.lua

Merge https://github.com/voxowl/particubes-private/pull/4667 first

Add category to item save

---

lua/modules/chat.lua
lua/modules/localevent.lua
lua/modules/menu.lua
lua/modules/textbubbles.lua

- chat messages not sent as regular Events anymore
- now sent with `System:SendChatMessage(message, recipients)`
- chat messages modified within `Client.Onchat` aren't sent anymore (developers will have to use Events manually)
- chat messages now have status: "pending", "ok", "error", "reported"
On the backend side, we're now storing and monitoring all sent chat messages.

chat improvements

---

lua/modules/uikit.lua

not 100% sure of the fix, but `image` is not defined

module uikit : fix Lua error

---

lua/docs/content/guides/index.yml

Fix download page link

---

lua/modules/item_editor.lua

Fix facemode paint

---

lua/modules/uitheme.lua

added oled ui theme 
_For real_

ui theme addon fix

---

lua/modules/chat.lua
lua/modules/ease.lua
lua/modules/localevent.lua
lua/modules/login.lua
lua/modules/menu.lua
lua/modules/modal.lua
lua/modules/system_api.lua
lua/modules/uikit.lua

Switching to a different system for text inputs, relying on host platform native text input components. 
The goal is to better support all keyboard (hardware and virtual) specificities & shortcuts.
NOTE: most of the changes in private repository, they will soon migrate here.

Improved text inputs

---

core/ray.c
core/ray.h
core/rigidBody.c
core/scene.c
core/scene.h
core/shape.c
core/shape.h
core/transform.c
core/transform.h

Contributes to https://github.com/cubzh/cubzh/issues/540

Remove pivot transform

---

bundle/fonts/NotoSansMono-Regular.ttf

Monospace font

---

lua/modules/alert.lua
lua/modules/cubzh.lua
lua/modules/menu.lua
lua/modules/phonenumbers.lua
lua/modules/signup.lua
lua/modules/system_api.lua

Contributes to #628 
- Forces users to pick an age with the slider
- Fixes "auto skip" when done waiting for parent approval
- Adds refresh countdown

Sign up improvements

---

lua/modules/cubzh.lua
lua/modules/time.lua

Fixes #587
- Fixes username sizes in friend cells (scale to fit)
- Fixes username labels becoming darker (we were not recycling them correctly, creating way too many labels)
- Adds likes and views in world cells
- Adds likes in item cells
- Add "last seen" labels in friend cells
- use loading animation instead of placeholder shapes

Home improvements

---

lua/modules/ui_avatar_editor.lua

fixes https://github.com/voxowl/particubes-private/issues/4905
We need to check that this change doesn't break anything...

avatar editor : fix bug with blue skin coming back when changing eyes

---

lua/modules/friends.lua

friends list : fix disappearing avatars for "newbie" users

---

lua/modules/avatar.lua

this is a suggestion of change

module avatar: fix didLoad callback for "get" func

---

deps/bgfx/README.md
deps/bgfx/bgfx/src/renderer_gl.cpp

From an open issue on bgfx repo: https://github.com/bkaradzic/bgfx/issues/3352
Workaround adapted on latest bgfx version & enabled only w/ `__VX_REWRITE_URLS_FOR_DISCORD`

Safari fix attempt

---

deps/libluau/build.sh

there are examples of commands at the top of build.sh

libluau: improve build script, allowing local dev

---

lua/docs/content/index.yml
lua/docs/content/media/cross-platform.mp4
lua/docs/content/media/glide-and-dance.mp4
lua/docs/content/media/jump-edit.mp4
lua/docs/content/media/jump-higher.mp4
lua/docs/content/media/mars.mp4
lua/docs/content/reference/pointer.yml
lua/docs/content/sample-scripts.yml
lua/docs/content/style/css/style.css
lua/docs/content/templates/head.tmpl
lua/docs/content/templates/menu.tmpl
lua/docs/content/templates/page.tmpl
lua/docs/content/templates/sidemenu.tmpl
lua/docs/docker-compose-dev.yml
lua/docs/webserver/page.go
lua/modules/controls.lua

Docs:
- Updates home page content
- Updates `Pointer` documentation (adding missing `Click` property)
- Updates page style

Docs update

---

lua/modules/animations.lua
lua/modules/avatar.lua
lua/modules/ease.lua

This PR contains important fixes in the `animations` module.
We were wrongly  iterating over all animations instead of only the ones playing to execute the `Tick` function and check for animation end conditions. 
The PR also contains a few optimizations, in `animations` and `ease` modules.

Fix animation system + optimizations

---

lua/modules/avatar.lua
lua/modules/ui_avatar_editor.lua

Fixes https://github.com/cubzh/cubzh/issues/620
- Fixes spots with wrong skin color when displaying noses
- Fixes wrong blue skin color saved when opening the editor and changing something other than skin
- Fixes eyes not being updated / displayed as expected in combination with "no nose" option

Fix avatar editor issues

---

lua/modules/ui_loading_animation.lua

Fixes that issue: 
(thank you @Donorhan for the report!)

fix bug in ui_loading_animation (instance not removed correctly)

---

lua/docs/content/reference/dev.yml

Adding sample code showing how to display FPS. 
Following conversation on Discord: https://discord.com/channels/355905150528913409/1371430988500176957

Docs: Add Dev.DisplayFPS sample code

---

core/transform.c
lua/modules/creations.lua
lua/modules/uikit.lua

- improves uikit shape node implementation 
- adds setBottomMargin accessor for text inputs (allows to show content between input and virtual)
- scroll improvements (using epsilon to stop useless refreshes)
- improvements and fixes in creation modal contents
- transform_utils_box_fit_recurse: do not ignore empty transforms

UI fixes and improvements
